name: Client-Side composite action
description: "Composite action for client side of LMS"

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:unit